[build]
  command = "npm run build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [[redirects]]
  from = "/v1/agents"
  to = "https://valorant-api.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}